#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# Deploy Client Script
# Automates building and deploying the FinLogia PWA for a specific client:
#   1. Reads config from clients.json
#   2. Writes pwa-client/.env.local and pwa-client/.firebaserc
#   3. Builds the Vue app
#   4. Deploys to Firebase Hosting
#
# Usage: ./deploy_client.sh <projectId>
# ─────────────────────────────────────────────────────────────────────────────

REGION="europe-west3"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PWA_DIR="${SCRIPT_DIR}/pwa-client"
CLIENTS_FILE="${SCRIPT_DIR}/clients.json"

# ─── Colors & helpers ─────────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
error()   { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# ─── Cleanup function ─────────────────────────────────────────────────────────

cleanup() {
  info "Restoring .env.local via git..."
  if [ -d "${PWA_DIR}/.git" ] || git -C "${PWA_DIR}" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git -C "${PWA_DIR}" restore .env.local || true
  else
    git restore "${PWA_DIR}/.env.local" || true
  fi
  
  # Clean up any leftover build directories if script was aborted
  rm -rf "${SCRIPT_DIR}/.build_"*
  
  success "Cleanup complete."
}

# Ensure cleanup runs even if the script fails or is aborted
trap cleanup EXIT

# ─── Prerequisites ────────────────────────────────────────────────────────────

for cmd in firebase node jq npm; do
  if ! command -v "$cmd" &>/dev/null; then
    error "'${cmd}' is required but not found. Please install it first."
  fi
done

if [[ ! -f "$CLIENTS_FILE" ]]; then
  error "clients.json not found. Run ./setup_client.sh first."
fi

# ─── Input: Project ID ───────────────────────────────────────────────────────

if [ "$#" -ne 1 ]; then
  error "Usage: $0 <projectId>"
fi

PROJECT_ID="$1"

# Extract client config from clients.json
CLIENT_CONFIG=$(jq -r ".[] | select(.projectId == \"$PROJECT_ID\")" "$CLIENTS_FILE")

if [[ -z "$CLIENT_CONFIG" ]]; then
  error "Project '$PROJECT_ID' not found in clients.json."
fi

API_KEY=$(echo "$CLIENT_CONFIG" | jq -r '.apiKey')
AUTH_DOMAIN=$(echo "$CLIENT_CONFIG" | jq -r '.authDomain')
STORAGE_BUCKET=$(echo "$CLIENT_CONFIG" | jq -r '.storageBucket')
MESSAGING_SENDER_ID=$(echo "$CLIENT_CONFIG" | jq -r '.messagingSenderId')
APP_ID=$(echo "$CLIENT_CONFIG" | jq -r '.appId')

CLIENT_SLUG="${PROJECT_ID#finlogia-}"
VITE_CLIENT_NAME=$(echo "$CLIENT_SLUG" | tr '-' ' ' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1')
BASE_URL="https://${REGION}-${PROJECT_ID}.cloudfunctions.net"

info "Deploying client: ${VITE_CLIENT_NAME} (${PROJECT_ID})"

# ─── Version Bump ─────────────────────────────────────────────────────────────

if [[ "${SKIP_VERSION_BUMP:-0}" != "1" ]]; then
  "${SCRIPT_DIR}/bump_version.sh"
fi

# ─── Pre-Deployment Checks ────────────────────────────────────────────────────

info "Running tests..."
if (cd "$PWA_DIR" && npm run test:run); then
  success "Tests passed"
else
  error "Tests failed. Fix failing tests before deploying."
fi

info "Running TypeScript type check..."
if (cd "$PWA_DIR" && npx vue-tsc --noEmit); then
  success "Type check passed"
else
  error "Type check failed. Fix TypeScript errors before deploying."
fi

# ─── Build & Deploy ───────────────────────────────────────────────────────────

# Create a unique work directory for this client's build to avoid race conditions
WORK_DIR="${SCRIPT_DIR}/.build_${PROJECT_ID}"
rm -rf "$WORK_DIR"
mkdir -p "$WORK_DIR"

# Copy files, excluding node_modules and dist to prevent symlink/build issues
rsync -a --exclude 'node_modules' --exclude 'dist' "${PWA_DIR}/" "$WORK_DIR/"

info "Writing ${WORK_DIR}/.env.local..."
cat > "${WORK_DIR}/.env.local" <<EOF
# Auto-generated by deploy_client.sh for ${PROJECT_ID}
VITE_FIREBASE_API_KEY="${API_KEY}"
VITE_FIREBASE_AUTH_DOMAIN="${AUTH_DOMAIN}"
VITE_FIREBASE_PROJECT_ID="${PROJECT_ID}"
VITE_FIREBASE_STORAGE_BUCKET="${STORAGE_BUCKET}"
VITE_FIREBASE_MESSAGING_SENDER_ID="${MESSAGING_SENDER_ID}"
VITE_FIREBASE_APP_ID="${APP_ID}"
VITE_FIREBASE_MEASUREMENT_ID=""
VITE_FIREBASE_BUCKET_FOLDER="uploads"
VITE_INVOICE_EXPIRY_DAYS=7

# Cloud Functions endpoints
VITE_BASE_URL=${BASE_URL}
VITE_SIGNED_UPLOAD_URL_PATH=/getSignedUploadUrl_v2
VITE_SIGNED_DOWNLOAD_URL_PATH=/getSignedDownloadUrl_v2
VITE_UPDATE_INVOICE_FIELDS_PATH=/updateInvoiceFields_v2
VITE_UPDATE_PAYMENT_STATUS_PATH=/updatePaymentStatus_v2
VITE_UPDATE_SUPPLIER_FIELDS_PATH=/updateSupplierFields_v2
VITE_ADD_FINANCIAL_ENTRY_PATH=/addFinancialEntry_v2
VITE_DELETE_FINANCIAL_ENTRY_PATH=/deleteFinancialEntry_v2
VITE_GET_FINANCIAL_REPORT_PATH=/getFinancialReport_v2
VITE_ADD_RECURRING_EXPENSE_PATH=/addRecurringExpense_v2
VITE_UPDATE_RECURRING_EXPENSE_PATH=/updateRecurringExpense_v2
VITE_GET_RECURRING_EXPENSES_PATH=/getRecurringExpenses_v2
VITE_EXPORT_INVOICES_PATH=/exportInvoices_v2

VITE_CLIENT_NAME="${VITE_CLIENT_NAME}"
EOF
success ".env.local written."

info "Writing ${WORK_DIR}/.firebaserc..."
cat > "${WORK_DIR}/.firebaserc" <<EOF
{
  "projects": {
    "default": "${PROJECT_ID}"
  }
}
EOF
success ".firebaserc written."

info "Installing dependencies..."
(cd "$WORK_DIR" && npm install)

info "Building production bundle..."
(cd "$WORK_DIR" && npm run build)

info "Deploying to Firebase Hosting..."
(cd "$WORK_DIR" && firebase deploy --only hosting --project "$PROJECT_ID")

# Cleanup work directory
rm -rf "$WORK_DIR"

echo ""
success "Client '${PROJECT_ID}' fully deployed!"
echo -e "   ${BLUE}URL:${NC} https://${PROJECT_ID}.web.app"
echo ""
